[[redirects]]
        from = "/api/*"
        to = "https://emerging-stories-backend.herokuapp.com/api/:splat"
        status = 200
        force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false